import van from "./mini-van.js"
import common from "./common.ts"
import { HTMLDocument } from "https://deno.land/x/deno_dom@v0.1.38/deno-dom-wasm.ts"

export default (doc: HTMLDocument) => {
  const {tags: {div, i, iframe, li, ol, p}} = van.vanWithDoc(doc)
  const {H1, H2, Url, VanJS} = common(doc)

  const Video = (src: string) => p({class: "video-wrapper"},
    iframe({src, frameborder: "0", allow: "accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture", allowfullscreen: ""}),
  )

  return div({id: "content"},
    H1(VanJS(), ": Media Coverage"),
    p("🙏🙏🙏 ", VanJS(), " is a personal project, which means I don't have the time and resources to promote it to a wider audience. My heartfelt gratitude extends towards to all content creators and tech bloggers who are helping spread good words about ", VanJS(), ". Your help is invaluable in our pursuit of ", VanJS(), "'s mission: ", i("Enabling everyone to build useful UI apps with a few lines of code, anywhere, any time, on any device.")),
    H2("Videos"),
    Video("https://www.youtube.com/embed/Oh2IEVqarHs"),
    Video("https://www.youtube.com/embed/GJAB2hp5psQ"),
    Video("https://www.youtube.com/embed/Fpwcsp1QXbM"),
    Video("https://www.youtube.com/embed/grUihkwvALg"),
    Video("https://www.youtube.com/embed/DO_5HDn9fQ4"),
    Video("https://www.youtube.com/embed/KXwcCFdwjHU"),
    Video("https://www.youtube.com/embed/2Oee-q5TKRU?start=1774"),
    Video("https://www.youtube.com/embed/ob5uZEV2_zA"),
    p("(", i("In Polish"), ")"),
    p({class: "video-wrapper"},
      iframe({src: "https://www.linkedin.com/embed/feed/update/urn:li:ugcPost:7069919877041410048?compact=1", height: "420", width: "100%", frameborder: "0", allowfullscreen: "", title: "Embedded post"}),
    ),
    Video("https://www.youtube.com/embed/er5er7zfMkg"),
    p("(", i("In Dutch"), ")"),
    p({class: "video-wrapper"},
      iframe({src: "//player.bilibili.com/player.html?aid=319967399&bvid=BV1iw411X7YZ&cid=1307016397&p=1&&autoplay=0", scrolling: "no", border: "0", frameborder: "no", framespacing: "0", allowfullscreen: "true"}),
    ),
    p("(", i("In Simplified Chinese"), ")"),
    p({class: "video-wrapper"},
      iframe({src: "//player.bilibili.com/player.html?aid=495545037&bvid=BV13K411474d&cid=1388577329&p=1&&autoplay=0", scrolling: "no", border: "0", frameborder: "no", framespacing: "0", allowfullscreen: "true"}),
    ),
    p("(", i("In Simplified Chinese"), ")"),
    H2("Articles / Podcasts"),
    ol(
      li(Url("https://youtu.be/eop7r4oV2gc?si=XrOmUcr7fTQX8H5C"), " (podcasts)"),
      li(Url("https://changelog.com/jsparty/277"), " (podcasts)"),
      li(Url("https://blog.stackademic.com/vanjs-the-ultra-lightweight-react-alternative-55c0f380376f")),
      li(Url("https://thenewstack.io/vanjs-a-minimalist-vanilla-javascript-ui-framework/")),
      li(Url("https://devm.io/javascript/javascript-vanjs-xin")),
      li(Url("https://www.linkedin.com/pulse/vanjs-reactive-ui-framework-without-reactjsx-luvimac%3F/")),
      li(Url("https://www.linkedin.com/posts/muneebhussainmodi_javascript-js-webdevelopment-activity-7109226447000469504-hlRg/")),
      li(Url("https://www.linkedin.com/posts/stefanofago_vanjs-a-09kb-grab-n-go-reactive-ui-framework-activity-7092964871117451264-RYnu/")),
      li(Url("https://www.smashingmagazine.com/2024/01/top-frontend-tools-2023/#vanjs-https-vanjs-org")),
      li(Url("https://risingstars.js.org/2023/en#section-framework")),
      li(Url("https://github.com/thoughtspile/awesome-tiny-js?tab=readme-ov-file#ui-frameworks")),
      li(Url("https://dhtmlx.medium.com/javascript-news-updates-and-tutorials-august-2023-edition-d9fda0b268df")),
      li(Url("https://javascript.plainenglish.io/exciting-updates-in-the-web-dev-71c52563cee0")),
      li(Url("https://javascriptweekly.com/issues/650")),
      li(Url("https://javascriptweekly.com/issues/639")),
      li(Url("https://javascriptweekly.com/issues/680")),
      li(Url("https://bytes.dev/archives/211")),
      li(Url("https://bytes.dev/archives/190")),
      li(Url("https://echojs.com/news/41772")),
      li(Url("https://wweb.dev/weekly/150")),
      li(Url("https://javascript.thisweekin.io/javascript-weekly-issue-83-31f1d5c6c57f")),
      li(Url("https://us3.campaign-archive.com/?u=4ad274b490aa6da8c2d29b775&id=887df01416")),
      li(Url("https://dev.to/vincenius/weekly-web-development-resources-150-5819")),
      li(Url("https://dev.to/darkwiiplayer/making-the-case-for-skooma-4n70")),
      li(Url("https://dev.to/nombrekeff/want-to-help-with-cardboard-jsts-vanilla-reactive-framework-jcl")),
      li(Url("https://dev.to/efpage/the-fantastic-speed-of-template-literals-4f0p")),
      li(Url("https://devm.io/javascript/javascript-user-friendly-web-apps")),
      li(Url("https://webtoolsweekly.com/archives/issue-521/")),
      li(Url("https://webtoolsweekly.com/archives/issue-544/")),
      li(Url("https://fully-faltoo.com/p/weekly-review-gollum/")),
      li(Url("https://unsuckjs.com/")),
      li(Url("https://enpitsulin.xlog.app/reactive-framework-less-than-100-lines"), " (", i("in Simplified Chinese"), ")"),
      li(Url("https://juejin.cn/post/7274492344522948642"), " (", i("in Simplified Chinese"), ")"),
      li(Url("https://juejin.cn/post/7269011652234592315"), " (", i("in Simplified Chinese"), ")"),
      li(Url("https://juejin.cn/post/7237702874880032826"), " (", i("in Simplified Chinese"), ")"),
      li(Url("https://juejin.cn/post/7239148708699865144"), " (", i("in Simplified Chinese"), ")"),
      li(Url("https://juejin.cn/post/7256397479646117947"), " (", i("in Simplified Chinese"), ")"),
      li(Url("https://juejin.cn/post/7329424129997127716"), " (", i("in Simplified Chinese"), ")"),
      li(Url("https://www.qinshenxue.com/article/vanjs-the-worlds-smallest-responsive-ui-framework.html"), " (", i("in Simplified Chinese"), ")"),
      li(Url("https://www.toutiao.com/article/7235535718448202301"), " (", i("in Simplified Chinese"), ")"),
      li(Url("https://zhuanlan.zhihu.com/p/633510308"), " (", i("in Simplified Chinese"), ")"),
      li(Url("https://zhuanlan.zhihu.com/p/633260358"), " (", i("in Simplified Chinese"), ")"),
      li(Url("https://zhuanlan.zhihu.com/p/630633744"), " (", i("in Simplified Chinese"), ")"),
      li(Url("https://www.cnblogs.com/xueweihan/p/17445043.html"), " (", i("in Simplified Chinese"), ")"),
      li(Url("https://segmentfault.com/a/1190000044087547"), " (", i("in Simplified Chinese"), ")"),
      li(Url("https://segmentfault.com/a/1190000044560268"), " (", i("in Simplified Chinese"), ")"),
      li(Url("https://mdhweekly.com/weekly/issue-0101"), " (", i("in Simplified Chinese"), ")"),
      li(Url("https://hkdeveloper.io/2023/05/26/%E5%89%B5%E6%96%B0%E9%96%8B%E6%BA%90ui%E6%A1%86%E6%9E%B6%EF%BC%9Avanjs-%E6%96%BCgithub%E4%B8%8A%E9%87%8B%E5%87%BA/"), " (", i("in Traditional Chinese"), ")"),
      li(Url("https://news.hada.io/topic?id=10202"), " (", i("in Korean"), ")"),
      li(Url("https://stupidk.com/dev-weekly-20230805/"), " (", i("in Korean"), ")"),
      li(Url("https://gall.dcinside.com/mgallery/board/view/?id=github&no=56798"), " (", i("in Korean"), ")"),
      li(Url("https://zenn.dev/k_log24/articles/f5e2d4321f0b98"), " (", i("in Japanese"), ")"),
      li(Url("https://zenn.dev/ryo_kawamata/articles/1ad6e51eed13ae"), " (", i("in Japanese"), ")"),
      li(Url("https://zenn.dev/daifukuninja/articles/79ff6fa650a535"), " (", i("in Japanese"), ")"),
      li(Url("https://qiita.com/tags/vanjs"), " (", i("in Japanese"), ")"),
      li(Url("https://qiita.com/mori_goq/items/364d63c861c796b6ac4b"), " (", i("in Japanese"), ")"),
      li(Url("http://var.blog.jp/archives/87712487.html"), " (", i("in Japanese"), ")"),
      li(Url("http://kachibito.net/useful-resource/vanjs"), " (", i("in Japanese"), ")"),
      li(Url("https://b.hatena.ne.jp/entry/s/github.com/vanjs-org/van"), " (", i("in Japanese"), ")"),
      li(Url("https://jser.info/2023/05/26/wrangler-v3.0.0-playwright-v1.34.0-typescript-5.2/"), " (", i("in Japanese"), ")"),
      li(Url("https://jser.info/2023/08/10/lighthouse-v11.0.0-astro-2.10view-transitions-sharpwebassembly/"), " (", i("in Japanese"), ")"),
      li(Url("https://stackshare.io/vanjs")),
      li(Url("https://www.libhunt.com/r/van")),
      li(Url("https://www.saashub.com/vanjs")),
      li(Url("https://kicksaas.cool/resource/vanjs")),
      li(Url("https://www.builtatlightspeed.com/theme/vanjs-org-mini-van")),
    ),
  )
}
